[project]
name = "epub2go"
version = "2.2.1"
description = "EPUB converter using wget, pandoc and python glue"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.12.3",
    "click>=8.1.8",
    "pyfzf>=0.3.1", # hasnt been updated for some time
    "requests==2.32.3",
    "tqdm>=4.67.1",
    "urllib3==2.2.2",
]
[project.scripts]
epub2go = "epub2go.convert:main"

[tool.setuptools]
include-package-data = true

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]

[tool.setuptools_scm]
# can be empty if no extra settings are needed, presence enables setuptools-scm
